### ISSUE TITLE
Disable Sign-Up? User management...?

### ISSUE THREAD

**Issue by fsociety3765** [bmcgonag/quant-ux-docker#2]
Thanks for all the great contributions you have made to the community. 

I have just deployed this without any issues so far. I agree this is an amazing piece of software. 

My one concern is user management. There doesn't seem to be any. Unless I have missed something. I can't seem to see any admin settings as such. I wouldn't want anyone to be able to sign up and would prefer to have that disabled if possible.

Is there a way to do this? Disable signup, and then as an admin user, create and manage standard users once logged in?

Thanks,

FS

**Comment by bmcgonag** [comment]
This is a better request over at the [main repo for the project](https://github.com/KlausSchaefers/quant-ux).  This is just the repo for dockerizing it.

Main Project repo is https://github.com/KlausSchaefers/quant-ux

**Comment by bmcgonag** [comment]
Closing, and hoping the request has been made at the main project.
