### ISSUE TITLE
arm64 docker image not built

### ISSUE THREAD

**Issue by IMPranshu** [bmcgonag/quant-ux-docker#8]
I saw that the docker image only supports amd64.

**Comment by bmcgonag** [comment]
Trying to build an Arm64 version now. Nothing to test on though.

**Comment by bmcgonag** [comment]
I have built the two parts. You'll need to adjust the images used in my docker-compose.yml file to be

`bmcgonag/qux-be-arm64:latest` for the backend
`bmcgonag/qux-fe-arm64:latest` for the frontend

I have no way to test these, so please let me know if you find issues when bringing them up, and / or if everything appears to work well.
